## [03] 넘파이

- 머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다.
- 선형대수는 수학뿐만 아니라 다른 영역의 자연과학 공학에서 널리 사용되고 있다.
- Numerical Python을 의미하는 넘파이(Numpy)는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지이다.
- 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장한다.
- 대량 데이터 기반의 과학과 공학 프로그램은 빠른 계산 능력이 매우 중요하다.
- 넘파이는 또한 C/C++과 같은 저수준 언어 기반의 호한 API를 제공
- 기존 C/C++ 기반의 타 프로그램과 데이터를 주고 받거나 API를 호출해 쉽게 통합할 수 있는 기능을 제공
- 넘파이는 매우 빠른 배열 연산을 보장해 주지만, 파이썬 언어 자체가 가지는 수행 성능의 제약이 있으므로 수행 성능이 매우 중요한 부분은 C/C++ 기반의 코드로 작성하고 이를 넘파이에서 호추라는 방식으로 쉽게 통합할 수 있다.
- 넘파이는 배열 기반의 연산은 물론이고 다양한 데이터 핸들링 기능을 제공한다.
- 넘파이를 이해하는 것은 파이썬 기반의 머신러닝은 매우 중요하다.
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 잇음은 물론이고, 이들 알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용하기 때문이다.

### 넘파이 ndarray 개요

In [1]:
# 넘파이 모듈 import
import numpy as np

- 넘파이의 기반 데이터 타입은 ndarray
- ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.
- 넘파이 ndarray()함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행한다.
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray배열의 차원까지 알 수 있다.

In [2]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array2 = np.array([[1,2,3,],[2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


- np.array() : ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환
- ndarray.shape : ndarray의 차원과 크기를 튜플(tuple) 형태로 나타냄
- array1 -> 1차원 array 3개
- array2 -> 2차원 array로, 2개의 로우와 3개의 칼럼으로 구성, 2*3=6개의 데이터
- array3 -> 1개의 로우와 3개의 칼럼으로 구성된 2차원

In [3]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


- 리스트 [ ]는 1차원
- fltmxm [[ ]]는 2차원

### ndarray의 데이터 타입

- ndarray내의 데이터 값은 숫자 값, 문자열 값, 불 값 등이 모두 가능
- 숫자형의 경우 int형(8,16,32 bit), float형(16,32,64,128 bit)
- 이보다 더 큰 숫자 값이나 정밀도를 위해 complex타입도 제공
- ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
- 한 개의 ndarray객체에 int와 float가 함께 있을 수 없다.
- ndarray내의 데이터 타입은 dtype 속성으로 확인할 수 있다.

In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- ndarray 내 데이터 값의 타입 변경 astype( ) 메서드를 이용할 수 있다.
- astype( )에 인자로 원하는 타입을 문자열로 지정하면 된다.
- 이렇게 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 더 절약해야 할 때 보통 이용된다.

In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


- arange( ) 함수는 파이썬 표준 함수인 range( )와 유사한 기능을 한다. 
- 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해준다.
- default 함수 인자는 stop값이며, 0부터 stop값인 10에서 -1을 더한 9까지 연속 숫자 값으로 구성된 1차원 ndarray를 만들어 준다,
- zeros( )는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다.
- ones( )는 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다.
- 함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다

In [9]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape( )

- reshape( ) aptjemsms ndarray를 특정 차원 및 크기로 변환

In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

- reshape( )는 지정된 사이즈로 변경이 불가능하면 오류 발생

In [12]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2.shape:',array2.shape)
array3 = array1.reshape(5,-1)
print('array3.shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


- 인자로 -1을 적용하는 경우 ndarray와 호환되는 새로운 shape로 변환해준다.
- array1.reshape(-1,5) : 로우 인자가 -1, 칼럼 인자 5 -> array1과 호환될 수 잇는 2차원 ndarray로 변환화되, 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환하라는 의미
- 10개의 1차원 데이터와 호환될 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로 2X5의 2차원 ndarrayfh qusghkgksms rjtdlek.
- array1.reshape(5,-1) : 고정된 5개의 로우에 맞는 칼럼은 2이므로 5X2의 2차원 ndarray로 변환

In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

- -1인자는 reshape(-1,1와 같은 형태로 자주 사용된다.
- reshape(-1,1)의 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.
- 여러개의 넘파이 ndarray는 stack이나 concat으로 결합할 대 각각의 ndarray의 형태를 통일해 유용하게 사용된다.

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5d"\n',array5.tolist())
print('array5 shape:\n',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5d"
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

- 1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
- 2. 슬라이싱(Slicing) : 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식이다. ':'기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 위치에 있는 데이터의 ndarray를 반환한다. 
- 3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다.
- 4. 불린 인덱싱(Boolean Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 잇는 데이터의 ndarray를 반환한다.

#### 단일 값 추출

In [15]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start = 1, stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [16]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [17]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [18]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값 : ', array2d[0,0])
print('(row=0, col=1) index 가리키는 값 : ', array2d[0,1])
print('(row=1, col=0) index 가리키는 값 : ', array2d[1,0])
print('(row=2, col=2) index 가리키는 값 : ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 :  1
(row=0, col=1) index 가리키는 값 :  2
(row=1, col=0) index 가리키는 값 :  4
(row=2, col=2) index 가리키는 값 :  9


#### 슬라이싱

- ':'기호를 이용해 연속한 데이터를 슬라이싱해서 추출
- 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray타입이다.

In [19]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- ':'기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주한다.
- ':'기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주한다.
- ':'기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주한다.

In [20]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [23]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape : ', array2d[0].shape, 'array2d[1] shape : ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape :  (3,) array2d[1] shape :  (3,)


#### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱
- 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

In [25]:
array1d = np.arange(start=1, stop=10)
# [ ]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d > 5 불링 인덱싱 결과 값 : ',array3)

array1d > 5 불링 인덱싱 결과 값 :  [6 7 8 9]


In [26]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ',array3)

불린 인덱스로 필터링 결과 :  [6 7 8 9]


In [28]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 : ',array4)

일반 인덱스로 필터링 결과 :  [6 7 8 9]


### 행렬의 정렬 - sort( )와 argsort( )

#### 행렬 정렬

In [30]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ', org_array)
# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array)

#ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬 : ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ', org_array)


원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [31]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [32]:
array2d = np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기

In [33]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


In [34]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices_desc)

행렬 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


In [35]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 :', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 행렬 내적(행렬 곱)

In [36]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬

In [37]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
